"""ncbi regulatory regions and tss

Revision ID: 0286ad6acfe7
Revises: 694fc671a0ec
Create Date: 2026-09-18 02:32:27.835258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0286ad6acfe7'
down_revision: Union[str, Sequence[str], None] = '694fc671a0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ncbi_regulatory_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chrom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', postgresql.INT4RANGE(), nullable=False),
    sa.Column('strand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regulatory_class', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ncbi_regulatory_regions_chrom'), 'ncbi_regulatory_regions', ['chrom'], unique=False)
    op.create_index(op.f('ix_ncbi_regulatory_regions_feature_id'), 'ncbi_regulatory_regions', ['feature_id'], unique=True)
    op.create_index('ix_ncbi_regulatory_regions_region', 'ncbi_regulatory_regions', ['region'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ncbi_regulatory_regions_regulatory_class'), 'ncbi_regulatory_regions', ['regulatory_class'], unique=False)
    op.create_table('ncbi_tss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chrom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('strand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id', 'chrom', 'position', name='uq_ncbi_tss_placement')
    )
    op.create_index(op.f('ix_ncbi_tss_chrom'), 'ncbi_tss', ['chrom'], unique=False)
    op.create_index(op.f('ix_ncbi_tss_gene_id'), 'ncbi_tss', ['gene_id'], unique=False)
    op.create_index(op.f('ix_ncbi_tss_transcript_id'), 'ncbi_tss', ['transcript_id'], unique=False)
    op.create_index(op.f('ix_ncbi_tss_transcript_type'), 'ncbi_tss', ['transcript_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ncbi_tss_transcript_type'), table_name='ncbi_tss')
    op.drop_index(op.f('ix_ncbi_tss_transcript_id'), table_name='ncbi_tss')
    op.drop_index(op.f('ix_ncbi_tss_gene_id'), table_name='ncbi_tss')
    op.drop_index(op.f('ix_ncbi_tss_chrom'), table_name='ncbi_tss')
    op.drop_table('ncbi_tss')
    op.drop_index(op.f('ix_ncbi_regulatory_regions_regulatory_class'), table_name='ncbi_regulatory_regions')
    op.drop_index('ix_ncbi_regulatory_regions_region', table_name='ncbi_regulatory_regions', postgresql_using='gist')
    op.drop_index(op.f('ix_ncbi_regulatory_regions_feature_id'), table_name='ncbi_regulatory_regions')
    op.drop_index(op.f('ix_ncbi_regulatory_regions_chrom'), table_name='ncbi_regulatory_regions')
    op.drop_table('ncbi_regulatory_regions')
    # ### end Alembic commands ###
