"""ucsc refgene regions

Revision ID: 06456de7ded0
Revises: da237969e4c3
Create Date: 2026-09-18 02:52:05.236899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06456de7ded0'
down_revision: Union[str, Sequence[str], None] = 'da237969e4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ucsc_refgene_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('assembly', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chrom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', postgresql.INT4RANGE(), nullable=False),
    sa.Column('strand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly', 'transcript_id', 'chrom', 'feature', name='uq_ucsc_refgene_regions_feature')
    )
    op.create_index(op.f('ix_ucsc_refgene_regions_assembly'), 'ucsc_refgene_regions', ['assembly'], unique=False)
    op.create_index(op.f('ix_ucsc_refgene_regions_chrom'), 'ucsc_refgene_regions', ['chrom'], unique=False)
    op.create_index(op.f('ix_ucsc_refgene_regions_feature'), 'ucsc_refgene_regions', ['feature'], unique=False)
    op.create_index(op.f('ix_ucsc_refgene_regions_gene_id'), 'ucsc_refgene_regions', ['gene_id'], unique=False)
    op.create_index('ix_ucsc_refgene_regions_region', 'ucsc_refgene_regions', ['region'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_ucsc_refgene_regions_transcript_id'), 'ucsc_refgene_regions', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ucsc_refgene_regions_transcript_id'), table_name='ucsc_refgene_regions')
    op.drop_index('ix_ucsc_refgene_regions_region', table_name='ucsc_refgene_regions', postgresql_using='gist')
    op.drop_index(op.f('ix_ucsc_refgene_regions_gene_id'), table_name='ucsc_refgene_regions')
    op.drop_index(op.f('ix_ucsc_refgene_regions_feature'), table_name='ucsc_refgene_regions')
    op.drop_index(op.f('ix_ucsc_refgene_regions_chrom'), table_name='ucsc_refgene_regions')
    op.drop_index(op.f('ix_ucsc_refgene_regions_assembly'), table_name='ucsc_refgene_regions')
    op.drop_table('ucsc_refgene_regions')
    # ### end Alembic commands ###
