"""reactome pathways, hierarchy and participations

Revision ID: 0d2d8539611c
Revises: acdb3d8b94c8
Create Date: 2026-09-18 03:00:46.519256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = '0d2d8539611c'
down_revision: Union[str, Sequence[str], None] = 'acdb3d8b94c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactome_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactome_pathways_name'), 'reactome_pathways', ['name'], unique=False)
    op.create_index(op.f('ix_reactome_pathways_stable_id'), 'reactome_pathways', ['stable_id'], unique=True)
    op.create_table('reactome_gene_pathways',
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('evidence_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['reactome_pathways.id'], ),
    sa.PrimaryKeyConstraint('gene_id', 'pathway_id')
    )
    op.create_index(op.f('ix_reactome_gene_pathways_evidence_code'), 'reactome_gene_pathways', ['evidence_code'], unique=False)
    op.create_index(op.f('ix_reactome_gene_pathways_gene_id'), 'reactome_gene_pathways', ['gene_id'], unique=False)
    op.create_index(op.f('ix_reactome_gene_pathways_pathway_id'), 'reactome_gene_pathways', ['pathway_id'], unique=False)
    op.create_table('reactome_pathway_relations',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['reactome_pathways.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['reactome_pathways.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_index(op.f('ix_reactome_pathway_relations_child_id'), 'reactome_pathway_relations', ['child_id'], unique=False)
    op.create_index(op.f('ix_reactome_pathway_relations_parent_id'), 'reactome_pathway_relations', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactome_pathway_relations_parent_id'), table_name='reactome_pathway_relations')
    op.drop_index(op.f('ix_reactome_pathway_relations_child_id'), table_name='reactome_pathway_relations')
    op.drop_table('reactome_pathway_relations')
    op.drop_index(op.f('ix_reactome_gene_pathways_pathway_id'), table_name='reactome_gene_pathways')
    op.drop_index(op.f('ix_reactome_gene_pathways_gene_id'), table_name='reactome_gene_pathways')
    op.drop_index(op.f('ix_reactome_gene_pathways_evidence_code'), table_name='reactome_gene_pathways')
    op.drop_table('reactome_gene_pathways')
    op.drop_index(op.f('ix_reactome_pathways_stable_id'), table_name='reactome_pathways')
    op.drop_index(op.f('ix_reactome_pathways_name'), table_name='reactome_pathways')
    op.drop_table('reactome_pathways')
    # ### end Alembic commands ###
