"""orphanet diseases, xrefs and disease genes

Revision ID: 3c49a3da16f6
Revises: 8f687435e62a
Create Date: 2026-09-18 02:45:08.658632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = '3c49a3da16f6'
down_revision: Union[str, Sequence[str], None] = '8f687435e62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orpha_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orpha_code', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disorder_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disorder_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orpha_diseases_disorder_type'), 'orpha_diseases', ['disorder_type'], unique=False)
    op.create_index(op.f('ix_orpha_diseases_name'), 'orpha_diseases', ['name'], unique=False)
    op.create_index(op.f('ix_orpha_diseases_orpha_code'), 'orpha_diseases', ['orpha_code'], unique=True)
    op.create_table('orpha_disease_genes',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('association_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('association_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_of_validation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['orpha_diseases.id'], ),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('disease_id', 'gene_id')
    )
    op.create_index(op.f('ix_orpha_disease_genes_association_type'), 'orpha_disease_genes', ['association_type'], unique=False)
    op.create_index(op.f('ix_orpha_disease_genes_disease_id'), 'orpha_disease_genes', ['disease_id'], unique=False)
    op.create_index(op.f('ix_orpha_disease_genes_gene_id'), 'orpha_disease_genes', ['gene_id'], unique=False)
    op.create_table('orpha_disease_xrefs',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['orpha_diseases.id'], ),
    sa.PrimaryKeyConstraint('disease_id', 'source', 'reference')
    )
    op.create_index(op.f('ix_orpha_disease_xrefs_disease_id'), 'orpha_disease_xrefs', ['disease_id'], unique=False)
    op.create_index(op.f('ix_orpha_disease_xrefs_reference'), 'orpha_disease_xrefs', ['reference'], unique=False)
    op.create_index(op.f('ix_orpha_disease_xrefs_source'), 'orpha_disease_xrefs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orpha_disease_xrefs_source'), table_name='orpha_disease_xrefs')
    op.drop_index(op.f('ix_orpha_disease_xrefs_reference'), table_name='orpha_disease_xrefs')
    op.drop_index(op.f('ix_orpha_disease_xrefs_disease_id'), table_name='orpha_disease_xrefs')
    op.drop_table('orpha_disease_xrefs')
    op.drop_index(op.f('ix_orpha_disease_genes_gene_id'), table_name='orpha_disease_genes')
    op.drop_index(op.f('ix_orpha_disease_genes_disease_id'), table_name='orpha_disease_genes')
    op.drop_index(op.f('ix_orpha_disease_genes_association_type'), table_name='orpha_disease_genes')
    op.drop_table('orpha_disease_genes')
    op.drop_index(op.f('ix_orpha_diseases_orpha_code'), table_name='orpha_diseases')
    op.drop_index(op.f('ix_orpha_diseases_name'), table_name='orpha_diseases')
    op.drop_index(op.f('ix_orpha_diseases_disorder_type'), table_name='orpha_diseases')
    op.drop_table('orpha_diseases')
    # ### end Alembic commands ###
