"""hgnc withdrawn entries

Revision ID: 3f3e7d360996
Revises: 3c49a3da16f6
Create Date: 2026-09-18 02:47:46.416359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3e7d360996'
down_revision: Union[str, Sequence[str], None] = '3c49a3da16f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hgnc_withdrawn',
    sa.Column('hgnc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('withdrawn_symbol', postgresql.CITEXT(), nullable=True),
    sa.Column('merged_into', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('hgnc_id')
    )
    op.create_index(op.f('ix_hgnc_withdrawn_withdrawn_symbol'), 'hgnc_withdrawn', ['withdrawn_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hgnc_withdrawn_withdrawn_symbol'), table_name='hgnc_withdrawn')
    op.drop_table('hgnc_withdrawn')
    # ### end Alembic commands ###
