"""smart domain annotation

Revision ID: 55b32d166a8f
Revises: 0d2d8539611c
Create Date: 2026-09-18 10:33:48.487634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55b32d166a8f'
down_revision: Union[str, Sequence[str], None] = '0d2d8539611c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniprot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('sequence_md5', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aa_length', sa.Integer(), nullable=False),
    sa.Column('crc_passed', sa.Boolean(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_analyses_gene_id'), 'smart_analyses', ['gene_id'], unique=False)
    op.create_index(op.f('ix_smart_analyses_uniprot_id'), 'smart_analyses', ['uniprot_id'], unique=True)
    op.create_table('smart_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('evalue', sa.Float(), nullable=True),
    sa.Column('feature_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['smart_analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'name', 'start', 'end', name='uq_smart_domains_feature')
    )
    op.create_index(op.f('ix_smart_domains_analysis_id'), 'smart_domains', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_smart_domains_feature_type'), 'smart_domains', ['feature_type'], unique=False)
    op.create_index(op.f('ix_smart_domains_name'), 'smart_domains', ['name'], unique=False)
    op.create_index(op.f('ix_smart_domains_visible'), 'smart_domains', ['visible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smart_domains_visible'), table_name='smart_domains')
    op.drop_index(op.f('ix_smart_domains_name'), table_name='smart_domains')
    op.drop_index(op.f('ix_smart_domains_feature_type'), table_name='smart_domains')
    op.drop_index(op.f('ix_smart_domains_analysis_id'), table_name='smart_domains')
    op.drop_table('smart_domains')
    op.drop_index(op.f('ix_smart_analyses_uniprot_id'), table_name='smart_analyses')
    op.drop_index(op.f('ix_smart_analyses_gene_id'), table_name='smart_analyses')
    op.drop_table('smart_analyses')
    # ### end Alembic commands ###
