"""hgmd regulatory, complex rearrangements, repeat variations

Revision ID: 694fc671a0ec
Revises: 93ef9b31763f
Create Date: 2026-09-18 02:21:49.478149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694fc671a0ec'
down_revision: Union[str, Sequence[str], None] = '93ef9b31763f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hgmd_complex_rearrangements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_complex_rearrangements_accession'), 'hgmd_complex_rearrangements', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_complex_rearrangements_gene_id'), 'hgmd_complex_rearrangements', ['gene_id'], unique=False)
    op.create_table('hgmd_regulatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('regulatory_sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_nucleotide', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vcf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_regulatory_accession'), 'hgmd_regulatory', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_regulatory_gene_id'), 'hgmd_regulatory', ['gene_id'], unique=False)
    op.create_table('hgmd_repeat_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('amplified_sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('normal_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pathological_range', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_repeat_variations_accession'), 'hgmd_repeat_variations', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_repeat_variations_gene_id'), 'hgmd_repeat_variations', ['gene_id'], unique=False)
    op.create_table('hgmd_complex_rearrangements_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_complex_rearrangements.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.create_table('hgmd_regulatory_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_regulatory.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.create_table('hgmd_repeat_variations_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_repeat_variations.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.add_column('hgmd_missense_nonsense', sa.Column('legacy_change', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hgmd_missense_nonsense', 'legacy_change')
    op.drop_table('hgmd_repeat_variations_publication')
    op.drop_table('hgmd_regulatory_publication')
    op.drop_table('hgmd_complex_rearrangements_publication')
    op.drop_index(op.f('ix_hgmd_repeat_variations_gene_id'), table_name='hgmd_repeat_variations')
    op.drop_index(op.f('ix_hgmd_repeat_variations_accession'), table_name='hgmd_repeat_variations')
    op.drop_table('hgmd_repeat_variations')
    op.drop_index(op.f('ix_hgmd_regulatory_gene_id'), table_name='hgmd_regulatory')
    op.drop_index(op.f('ix_hgmd_regulatory_accession'), table_name='hgmd_regulatory')
    op.drop_table('hgmd_regulatory')
    op.drop_index(op.f('ix_hgmd_complex_rearrangements_gene_id'), table_name='hgmd_complex_rearrangements')
    op.drop_index(op.f('ix_hgmd_complex_rearrangements_accession'), table_name='hgmd_complex_rearrangements')
    op.drop_table('hgmd_complex_rearrangements')
    # ### end Alembic commands ###
