"""omim genes

Revision ID: 8f687435e62a
Revises: 9d8e9096513e
Create Date: 2026-09-18 02:42:18.315974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = '8f687435e62a'
down_revision: Union[str, Sequence[str], None] = '9d8e9096513e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('omim_genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mim_number', sa.Integer(), nullable=False),
    sa.Column('entry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=True),
    sa.Column('ncbi_gene_id', sa.Integer(), nullable=True),
    sa.Column('ensembl_gene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_omim_genes_ensembl_gene_id'), 'omim_genes', ['ensembl_gene_id'], unique=False)
    op.create_index(op.f('ix_omim_genes_entry_type'), 'omim_genes', ['entry_type'], unique=False)
    op.create_index(op.f('ix_omim_genes_gene_id'), 'omim_genes', ['gene_id'], unique=False)
    op.create_index(op.f('ix_omim_genes_mim_number'), 'omim_genes', ['mim_number'], unique=True)
    op.create_index(op.f('ix_omim_genes_ncbi_gene_id'), 'omim_genes', ['ncbi_gene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_omim_genes_ncbi_gene_id'), table_name='omim_genes')
    op.drop_index(op.f('ix_omim_genes_mim_number'), table_name='omim_genes')
    op.drop_index(op.f('ix_omim_genes_gene_id'), table_name='omim_genes')
    op.drop_index(op.f('ix_omim_genes_entry_type'), table_name='omim_genes')
    op.drop_index(op.f('ix_omim_genes_ensembl_gene_id'), table_name='omim_genes')
    op.drop_table('omim_genes')
    # ### end Alembic commands ###
