"""core tables and hgmd

Revision ID: 93ef9b31763f
Revises: 
Create Date: 2026-09-18 02:13:51.069512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93ef9b31763f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # hand-added: the gene symbol columns below are citext, so the extension has to come first
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hgnc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locus_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locus_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ncbi_gene_id', sa.Integer(), nullable=True),
    sa.Column('ensembl_gene_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ucsc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uniprot_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('refseq_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ccds_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('mgd_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genes_ensembl_gene_id'), 'genes', ['ensembl_gene_id'], unique=False)
    op.create_index(op.f('ix_genes_hgnc_id'), 'genes', ['hgnc_id'], unique=True)
    op.create_index(op.f('ix_genes_locus_group'), 'genes', ['locus_group'], unique=False)
    op.create_index(op.f('ix_genes_ncbi_gene_id'), 'genes', ['ncbi_gene_id'], unique=False)
    op.create_index(op.f('ix_genes_symbol'), 'genes', ['symbol'], unique=True)
    op.create_index(op.f('ix_genes_ucsc_id'), 'genes', ['ucsc_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pubmed_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_pubmed_id'), 'publications', ['pubmed_id'], unique=True)
    op.create_table('gene_aliases',
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('alias', postgresql.CITEXT(), nullable=False),
    sa.Column('alias_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('gene_id', 'alias', 'alias_type')
    )
    op.create_index(op.f('ix_gene_aliases_alias'), 'gene_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_gene_aliases_gene_id'), 'gene_aliases', ['gene_id'], unique=False)
    op.create_table('hgmd_gross_indels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dna_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_nucleotide', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_protein', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vcf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_gross_indels_accession'), 'hgmd_gross_indels', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_gross_indels_gene_id'), 'hgmd_gross_indels', ['gene_id'], unique=False)
    op.create_index(op.f('ix_hgmd_gross_indels_variant_type'), 'hgmd_gross_indels', ['variant_type'], unique=False)
    op.create_table('hgmd_missense_nonsense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('codon_change', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('aa_change', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_nucleotide', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_protein', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vcf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_missense_nonsense_accession'), 'hgmd_missense_nonsense', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_missense_nonsense_gene_id'), 'hgmd_missense_nonsense', ['gene_id'], unique=False)
    op.create_table('hgmd_small_indels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('variant_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_nucleotide', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_protein', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vcf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_small_indels_accession'), 'hgmd_small_indels', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_small_indels_gene_id'), 'hgmd_small_indels', ['gene_id'], unique=False)
    op.create_index(op.f('ix_hgmd_small_indels_variant_type'), 'hgmd_small_indels', ['variant_type'], unique=False)
    op.create_table('hgmd_splicing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('accession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_class', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phenotype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('xrefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('splicing_mutation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hgvs_nucleotide', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vcf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hgmd_splicing_accession'), 'hgmd_splicing', ['accession'], unique=True)
    op.create_index(op.f('ix_hgmd_splicing_gene_id'), 'hgmd_splicing', ['gene_id'], unique=False)
    op.create_table('hgmd_gross_indels_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_gross_indels.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.create_table('hgmd_missense_nonsense_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_missense_nonsense.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.create_table('hgmd_small_indels_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_small_indels.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    op.create_table('hgmd_splicing_publication',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('annotation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['hgmd_splicing.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hgmd_splicing_publication')
    op.drop_table('hgmd_small_indels_publication')
    op.drop_table('hgmd_missense_nonsense_publication')
    op.drop_table('hgmd_gross_indels_publication')
    op.drop_index(op.f('ix_hgmd_splicing_gene_id'), table_name='hgmd_splicing')
    op.drop_index(op.f('ix_hgmd_splicing_accession'), table_name='hgmd_splicing')
    op.drop_table('hgmd_splicing')
    op.drop_index(op.f('ix_hgmd_small_indels_variant_type'), table_name='hgmd_small_indels')
    op.drop_index(op.f('ix_hgmd_small_indels_gene_id'), table_name='hgmd_small_indels')
    op.drop_index(op.f('ix_hgmd_small_indels_accession'), table_name='hgmd_small_indels')
    op.drop_table('hgmd_small_indels')
    op.drop_index(op.f('ix_hgmd_missense_nonsense_gene_id'), table_name='hgmd_missense_nonsense')
    op.drop_index(op.f('ix_hgmd_missense_nonsense_accession'), table_name='hgmd_missense_nonsense')
    op.drop_table('hgmd_missense_nonsense')
    op.drop_index(op.f('ix_hgmd_gross_indels_variant_type'), table_name='hgmd_gross_indels')
    op.drop_index(op.f('ix_hgmd_gross_indels_gene_id'), table_name='hgmd_gross_indels')
    op.drop_index(op.f('ix_hgmd_gross_indels_accession'), table_name='hgmd_gross_indels')
    op.drop_table('hgmd_gross_indels')
    op.drop_index(op.f('ix_gene_aliases_gene_id'), table_name='gene_aliases')
    op.drop_index(op.f('ix_gene_aliases_alias'), table_name='gene_aliases')
    op.drop_table('gene_aliases')
    op.drop_index(op.f('ix_publications_pubmed_id'), table_name='publications')
    op.drop_table('publications')
    op.drop_index(op.f('ix_genes_ucsc_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_symbol'), table_name='genes')
    op.drop_index(op.f('ix_genes_ncbi_gene_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_locus_group'), table_name='genes')
    op.drop_index(op.f('ix_genes_hgnc_id'), table_name='genes')
    op.drop_index(op.f('ix_genes_ensembl_gene_id'), table_name='genes')
    op.drop_table('genes')
    # ### end Alembic commands ###
