"""uniprot basic infos

Revision ID: 9d8e9096513e
Revises: 0286ad6acfe7
Create Date: 2026-09-18 02:37:53.454447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d8e9096513e'
down_revision: Union[str, Sequence[str], None] = '0286ad6acfe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uniprot_basic_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniprot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ec_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('canonical_aa_length', sa.Integer(), nullable=True),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subcellular_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ensembl_gene_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cofactors', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('tissues', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('secondary_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uniprot_basic_infos_ec_number'), 'uniprot_basic_infos', ['ec_number'], unique=False)
    op.create_index(op.f('ix_uniprot_basic_infos_gene_id'), 'uniprot_basic_infos', ['gene_id'], unique=False)
    op.create_index(op.f('ix_uniprot_basic_infos_uniprot_id'), 'uniprot_basic_infos', ['uniprot_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uniprot_basic_infos_uniprot_id'), table_name='uniprot_basic_infos')
    op.drop_index(op.f('ix_uniprot_basic_infos_gene_id'), table_name='uniprot_basic_infos')
    op.drop_index(op.f('ix_uniprot_basic_infos_ec_number'), table_name='uniprot_basic_infos')
    op.drop_table('uniprot_basic_infos')
    # ### end Alembic commands ###
