"""refgene region as part of the key

Revision ID: a81dfb7eede2
Revises: 06456de7ded0
Create Date: 2026-09-18 02:52:25.108558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = 'a81dfb7eede2'
down_revision: Union[str, Sequence[str], None] = '06456de7ded0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ucsc_refgene_regions_feature'), 'ucsc_refgene_regions', type_='unique')
    op.create_unique_constraint('uq_ucsc_refgene_regions_feature', 'ucsc_refgene_regions', ['assembly', 'transcript_id', 'chrom', 'feature', 'region'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ucsc_refgene_regions_feature', 'ucsc_refgene_regions', type_='unique')
    op.create_unique_constraint(op.f('uq_ucsc_refgene_regions_feature'), 'ucsc_refgene_regions', ['assembly', 'transcript_id', 'chrom', 'feature'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
