"""kegg pathways and memberships

Revision ID: acdb3d8b94c8
Revises: a81dfb7eede2
Create Date: 2026-09-18 02:58:50.299221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = 'acdb3d8b94c8'
down_revision: Union[str, Sequence[str], None] = 'a81dfb7eede2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kegg_pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kegg_pathway_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kegg_pathways_category'), 'kegg_pathways', ['category'], unique=False)
    op.create_index(op.f('ix_kegg_pathways_kegg_pathway_id'), 'kegg_pathways', ['kegg_pathway_id'], unique=True)
    op.create_index(op.f('ix_kegg_pathways_name'), 'kegg_pathways', ['name'], unique=False)
    op.create_table('kegg_gene_pathways',
    sa.Column('gene_id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.ForeignKeyConstraint(['pathway_id'], ['kegg_pathways.id'], ),
    sa.PrimaryKeyConstraint('gene_id', 'pathway_id')
    )
    op.create_index(op.f('ix_kegg_gene_pathways_gene_id'), 'kegg_gene_pathways', ['gene_id'], unique=False)
    op.create_index(op.f('ix_kegg_gene_pathways_pathway_id'), 'kegg_gene_pathways', ['pathway_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kegg_gene_pathways_pathway_id'), table_name='kegg_gene_pathways')
    op.drop_index(op.f('ix_kegg_gene_pathways_gene_id'), table_name='kegg_gene_pathways')
    op.drop_table('kegg_gene_pathways')
    op.drop_index(op.f('ix_kegg_pathways_name'), table_name='kegg_pathways')
    op.drop_index(op.f('ix_kegg_pathways_kegg_pathway_id'), table_name='kegg_pathways')
    op.drop_index(op.f('ix_kegg_pathways_category'), table_name='kegg_pathways')
    op.drop_table('kegg_pathways')
    # ### end Alembic commands ###
