"""orpha disease gene keyed by association type

Revision ID: da237969e4c3
Revises: 3f3e7d360996
Create Date: 2026-09-18 02:48:32.349227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerate writes sqlmodel.sql.sqltypes.AutoString for every str column


# revision identifiers, used by Alembic.
revision: str = 'da237969e4c3'
down_revision: Union[str, Sequence[str], None] = '3f3e7d360996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # hand-added: autogenerate sees the NOT NULL but not the primary key it belongs to - alembic
    # does not compare primary keys at all, which is why the generated diff gets read every time
    op.execute("DELETE FROM orpha_disease_genes WHERE association_type IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orpha_disease_genes', 'association_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
    op.drop_constraint('orpha_disease_genes_pkey', 'orpha_disease_genes', type_='primary')
    op.create_primary_key('orpha_disease_genes_pkey', 'orpha_disease_genes',
                          ['disease_id', 'gene_id', 'association_type'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('orpha_disease_genes_pkey', 'orpha_disease_genes', type_='primary')
    op.create_primary_key('orpha_disease_genes_pkey', 'orpha_disease_genes', ['disease_id', 'gene_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orpha_disease_genes', 'association_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
