update therrell_incidences set cases=105, screens=25026374, avg_incidence_per_mil_us_states= 4.1, stdev_incidence_per_mil_us_states= 5.5  where name_short='PROP';
update therrell_incidences set cases=12, screens=24123697, avg_incidence_per_mil_us_states= 0.3, stdev_incidence_per_mil_us_states= 0.9  where name_short='BKT';
update therrell_incidences set cases=158, screens=31238787, avg_incidence_per_mil_us_states= 3.5, stdev_incidence_per_mil_us_states= 4.6  where name_short='MSUD';
update therrell_incidences set cases=265, screens=24460145, avg_incidence_per_mil_us_states= 8.4, stdev_incidence_per_mil_us_states= 9.0  where name_short='GA-1';
update therrell_incidences set cases=422, screens=28597455, avg_incidence_per_mil_us_states=20.2, stdev_incidence_per_mil_us_states=24.2  where name_short='BIO';
update therrell_incidences set cases=67, screens=24370414, avg_incidence_per_mil_us_states= 3.7, stdev_incidence_per_mil_us_states= 6.2  where name_short='LCHADD';
update therrell_incidences set cases=380, screens=28577469, avg_incidence_per_mil_us_states=21.2, stdev_incidence_per_mil_us_states=17.4  where name_short='VLCADD';
update therrell_incidences set cases=58, screens=23799921, avg_incidence_per_mil_us_states= 1.7, stdev_incidence_per_mil_us_states= 3.3  where name_short='CBL A,B';
update therrell_incidences set cases=633, screens=24456304, avg_incidence_per_mil_us_states=22.8, stdev_incidence_per_mil_us_states=25.7  where name_short='3-MCC';
update therrell_incidences set cases=82, screens=25012585, avg_incidence_per_mil_us_states= 4.1, stdev_incidence_per_mil_us_states= 4.6  where name_short='ASA';
update therrell_incidences set cases=1791, screens=41335425, avg_incidence_per_mil_us_states=49.6, stdev_incidence_per_mil_us_states=26.7  where name_short='PKU';
update therrell_incidences set cases=691, screens=40265799, avg_incidence_per_mil_us_states=18.1, stdev_incidence_per_mil_us_states=17.8  where name_short='PKU Variant';
update therrell_incidences set cases=1554, screens=27597936, avg_incidence_per_mil_us_states=62.6, stdev_incidence_per_mil_us_states=29.1  where name_short='MCADD';
update therrell_incidences set cases=64, screens=29230466, avg_incidence_per_mil_us_states= 1.9, stdev_incidence_per_mil_us_states= 2.9  where name_short='HCY';
update therrell_incidences set cases=179, screens=20908664, avg_incidence_per_mil_us_states= 8.7, stdev_incidence_per_mil_us_states=13.7  where name_short='CUD';
update therrell_incidences set cases=154, screens=24509159, avg_incidence_per_mil_us_states= 5.5, stdev_incidence_per_mil_us_states= 7.4  where name_short='IVA';
update therrell_incidences set cases=158, screens=25219021, avg_incidence_per_mil_us_states= 4.8, stdev_incidence_per_mil_us_states= 5.5  where name_short='MUT';
update therrell_incidences set cases=12, screens=23134961, avg_incidence_per_mil_us_states= 0.5, stdev_incidence_per_mil_us_states= 1.7  where name_short='MCD';
update therrell_incidences set cases=770, screens=41133320, avg_incidence_per_mil_us_states=26.1, stdev_incidence_per_mil_us_states=36.5  where name_short='GALT';
update therrell_incidences set cases=36, screens=24521197, avg_incidence_per_mil_us_states= 2.2, stdev_incidence_per_mil_us_states= 5.5  where name_short='TYR-I';
update therrell_incidences set cases=16, screens=24456304, avg_incidence_per_mil_us_states= 0.5, stdev_incidence_per_mil_us_states= 1.2  where name_short='HMG';
update therrell_incidences set cases=1045, screens=26079853, avg_incidence_per_mil_us_states=48.4, stdev_incidence_per_mil_us_states=61.7  where name_short='Partial BIO';
update therrell_incidences set cases=13, screens=23693387, avg_incidence_per_mil_us_states= 0.4, stdev_incidence_per_mil_us_states= 1.0  where name_short='TFP';
update therrell_incidences set cases=128, screens=24908665, avg_incidence_per_mil_us_states= 6.1, stdev_incidence_per_mil_us_states= 7.2  where name_short='CIT';
